Better error handling support

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,7 +38,11 @@ jobs:
           
       - name: Running samloader-actions
         run: |
-          bash sam.sh      
+          bash sam.sh
+          if [ $? -ne 0 ]; then
+            echo "Error executing sam.sh. Stopping workflow." >&2
+            exit 1
+          fi
 
       - name: Uploading zip
         uses: actions/upload-artifact@v4
@@ -61,4 +65,4 @@ jobs:
             <b>Device :</b> ${{ env.MODEL }}                       
             <b>From Repository:</b> <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>
             
-            <b>Powered by:</b> <a href="https://github.com/ravindu644/samloader-actions">samloader-actions</a>            
+            <b>Powered by:</b> <a href="https://github.com/ravindu644/samloader-actions">samloader-actions</a>
